[package]
name = "ziggurat-core-utils"
version = "0.1.0"
edition = "2021"

homepage = "https://github.com/runziggurat/ziggurat-core"
repository = "https://github.com/runziggurat/ziggurat-core"

description = "Utils package for ziggurat based projects"

[dependencies]
