on:
  workflow_call:
    inputs:
      filter:
        type: string
jobs:
  viz-state:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      FILTER: ${{ inputs.filter }}
    steps:
      - uses: Swatinem/rust-cache@v2
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: runziggurat/crunchy
      - uses: actions/download-artifact@v3
        with:
          name: latest-result
      - if: ${{ inputs.filter != '' }}
        name: Generate filtered state
        run: cargo run --release -- -f $FILTER -i latest.json -o latest.viz.json
      - if: ${{ inputs.filter == '' }}
        name: Generate unfiltered state
        run: cargo run --release -- -i latest.json -o latest.viz.json
      - uses: actions/upload-artifact@v3
        with:
          name: latest-result
          path: latest.viz.json
