on:
  workflow_call:
    inputs:
      filter:
        type: string
jobs:
  viz-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: latest-result
      - run: rustup toolchain install stable --profile minimal
      - uses: actions/checkout@v3
        with:
          repository: runziggurat/crunchy
      - if: ${{ inputs.filter != "" }}
        name: Generate filtered state
        run: cargo run --release -- -f {{ inputs.filter }} -i latest.json -o latest.viz.json
      - if: ${{ inputs.filter == "" }}
        name: Generate unfiltered state
        run: cargo run --release -- -i latest.json -o latest.viz.json
      - uses: actions/upload-artifact@v3
        with:
          name: latest-result
          path: latest.viz.json
