name: basics

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basics:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        steps:
          - name: check
            run: cargo check --all-targets
          - name: fmt
            run: cargo +nightly fmt --all -- --check
          - name: clippy
            run: cargo clippy --all-targets -- -D warnings
          - name: sort
            run: |
              cargo install cargo-sort
              cargo sort
              git diff --exit-code
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: ${{ matrix.steps.name }}
        run: |
          nix develop --command \
          ${{ matrix.steps.run }}
